# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /deployment/api

# Copy the current directory contents into the container at /deployment/api
COPY . /deployment/api
COPY . /deployment/models

# Install the necessary packages
RUN pip --no-cache-dir install fastapi uvicorn scikit-learn pandas

COPY . .
# Expose the port that FastAPI will run on
EXPOSE 8000

# Command to run the API using uvicorn
CMD ["uvicorn", "deployment.api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

